import socket
import sys
import hashlib
import random
from pyDes import *
from hashEngine import HashEngine
from cryptoEngine import CryptoEngine

ID = "2"

bob_sock = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
trent_sock = socket.socket(socket.AF_INET, socket.SOCK_STREAM)

bob_address = ('localhost', 4000)
trent_address = ('localhost', 3000)

NONCE = str(random.randint(100000, 999999))
msg = "To jest wiadomosc klienta do servera"

hash_engine = HashEngine()
crypto_engine_trent = CryptoEngine("12345678")


def get_response(sock):
    response = sock.recv(512)
    if response:
        return response

def get_id(response):
    params = response.split(',')
    return params[0]

def get_nonce(response):
    params = response.split(',')
    return params[1].strip()

def send_request(sock, data):
    sock.sendall(data)

def get_session_key(data):
    params = data.split(',')
    return params[0]

def check_response(response):
    if response[::-1] == msg:
        print "Response correct."
    else:
        print "Response wrong."
    

print 'Connecting to Bob on: %s port %s' % bob_address
bob_sock.connect(bob_address)

print 'Connecting to Trent on: %s port %s' % trent_address
trent_sock.connect(trent_address)

try:
  # Getting information from Bob
  response = get_response(bob_sock)
  bob_id = get_id(response)
  bob_nonce = get_nonce(response)

  # Params sended to TRENT (id_alice, id_bob, nonce_a, nonce_b)
  params_for_trent = [ID, bob_id, NONCE, bob_nonce]
  params_message = ','.join(params_for_trent)

  print 'Sending connection information to Trent'
  send_request(trent_sock, params_message)

  print 'Getting Session key generated by Trent.'
  message_for_me = get_response(trent_sock)

  print 'Message for me received. Sending confirmation.'
  send_request(trent_sock, "Recived")

  message_for_bob = get_response(trent_sock)
  print 'Message for Bob received. Sending confirmation.'

  # Getting SESSION KEY from trent message
  decrypted_data = crypto_engine_trent.decrypt(message_for_me)
  SESSION_KEY = get_session_key(decrypted_data)
  crypto_engine_sesion = CryptoEngine(SESSION_KEY)

  print "Sending session key to Bob."
  send_request(bob_sock, message_for_bob)


  # display message from server
  if get_response(bob_sock):
    print "Authentication proces.."

  # send user name
  user_name = raw_input('Type your login: ')
  send_request(bob_sock, user_name)

  # get nonce from server
  nonce = get_response(bob_sock)

  # get user password
  password = raw_input('Type your password: ')

  # generate hash 
  secured_password = hash_engine.hahs_function(password)
  user_hash = hash_engine.generate_hash(nonce, secured_password)

  # send user_hash to server
  send_request(bob_sock, user_hash) 

  # get response with hash to compare
  hash_from_server = get_response(bob_sock)

  # compare hash to authenticate server
  alice_hash = hash_engine.generate_hash(secured_password, nonce)
  if hash_engine.compare_hashes(hash_from_server, alice_hash):
      print "Authentication succeeded! Server authenticated!"
      print 'Sending Request: ' + msg
      encrypted_msg = crypto_engine_sesion.encrypt(msg)
      send_request(bob_sock, encrypted_msg)
      response = get_response(bob_sock)
      decrypted_response = crypto_engine_sesion.decrypt(response)
      print "Response: " + decrypted_response
      print "Checking if correct response.."
      check_response(decrypted_response)
  else:
      print "Authentication failed"

finally:
    print 'closing socket'
    bob_sock.close()
    # trent_sock.close()